### ISSUE TITLE
LSL/LSR, JMP, HALT

### ISSUE THREAD

**Issue by silaslenz** [Jethro95/TSEA83_Graphing_Calculator#16]

**Comment by felixharnstrom** [comment]
JMP implemented in 8f0304b8c63c797c158ec3a3725a979a678812c2
LSL/LSR implemented in 59fc590a16694f1d1f6c8ae02e3eb747396f5751

**Comment by silaslenz** [comment]
All except HALT done. HALT is wontfix.
