### ISSUE TITLE
ALU based instructions

### ISSUE THREAD

**Issue by silaslenz** [Jethro95/TSEA83_Graphing_Calculator#7]

**Comment by silaslenz** [comment]
ADD/SUB

AND/ASL/ASR

**Comment by silaslenz** [comment]
ADD/SUB in 6c2ba01285388a4d54437ca7592e306029006b42
AND in 8df89c976206ed0a0d407ab610b30a8a103ee496

**Comment by felixharnstrom** [comment]
ASR/ASL in d072f1f5c542fa7b420323ea268b13e3fd70338b

**Comment by silaslenz** [comment]
All done. (Float inst removed, see issue #4 )
