### ISSUE TITLE
Jump instructions. 

### ISSUE THREAD

**Issue by silaslenz** [Jethro95/TSEA83_Graphing_Calculator#8]

**Comment by silaslenz** [comment]
BEQ/BMI/BNE/BRA/BRF

**Comment by felixharnstrom** [comment]
Added in 6cdfcfd649b48b25bec25a87e7e6f85b0b1bdb79 (and some faulty syntax fixed in 27261ce76ec8cf168897d64db036977bb363f0c8) but untested. Keeping this open until then.

**Comment by Jethro95** [comment]
All instructions working as of d7b9b0cafcbc0feb2e94b79363619e828f5109c7

**Comment by felixharnstrom** [comment]
All instructions working as of d7b9b0cafcbc0feb2e94b79363619e828f5109c7
